### ISSUE TITLE
Screeenly doesn't work for many URL's

### ISSUE THREAD

**Issue by zigojacko** [stefanzweifel/screeenly#62] opened 2016-08-17 15:03 UTC
I take it this is no longer maintained/supported seeing as your own server is throwing an error trying to show thumbshot for many URL's now...? Been like this for a while. It just isn't usable on a production site currently and we [originally reported this back in Feb](https://github.com/stefanzweifel/screeenly/issues/44).

**Comment by stefanzweifel** [comment] 2016-08-17 15:30
Hey

I still support screeenly. It's not dead! Can you send me some of your urls here or by mail?

We use screeenly in production and haven't any issues so far.

And as mentioned in the other issue, the problem is deeply burried in phantomjs itself.

**Comment by zigojacko** [comment] 2016-08-17 15:39
Ah, that is great to hear! Thanks for your quick reply.

Please find below just a small selection that don't seem to work. We have tested with loads though and more fail than do actually work it seems.

`
http://showthebride.com/
http://strangenessandcharm.co.uk/
http://www.charliemoos.co.uk/blog/
https://www.designhaven.co.uk/
http://blog.monkey-feet.com/
`

Edit:

That being said, I have now just run these domains through [Try Screeenly](http://screeenly.com/try) and they are now working (whereas earlier and yesterday, they weren't)...

They are still not loading on our website though but perhaps this might be caching related (looking into this).

Has there been any downtime with the API at all or something similar?

**Comment by stefanzweifel** [comment] 2016-08-17 15:48
Not that I'm aware of (Would like to add a status-page like https://status.github.com).
DigitalOcean Usage also looks okay.

May I ask, how you interact with screeenly on your end? Do you use `wnx/screeenlyClient` or your own implementation?

**Comment by evince-development** [comment] 2016-08-24 10:31
We have used screeenly api for getting thumb-shots. But some it is not giving thumb-shots in response for some sites.

**Comment by stefanzweifel** [comment] 2016-08-24 11:01
@evince-development Do you have any URLs to share? I want to take some time this week to do some testing and any URL which failed to generate URLs might be a help.

**Comment by zigojacko** [comment] 2016-08-25 13:48
@stefanzweifel it is literally any URL. Right now, even your pre-filled laravel.com URL isn't working in your tool (see attached screenshot). Happens with tons and tons of URL's so it isn't an issue with the websites. Gave a selection above as an example though.

![screeenly-bug](https://cloud.githubusercontent.com/assets/849735/17971479/efcb5bb4-6ad2-11e6-9eed-1834843dad64.png)

**Comment by stefanzweifel** [comment] 2016-08-25 13:52
@zigojacko Thanks again for the feedback. This is so weird. The `/try` page works for me (see screenshot).

Had a stressfull week, but I will sit down this evening and try some stuff. As stated in other issues screeenly currently uses PhantomJs and this "bug" is more than 2 years old and nothing happens.

`chrome-headless` is currently emerging and I will try to implement it with screeenly. Updates will follow.

**Comment by zigojacko** [comment] 2016-08-26 08:57
@stefanzweifel yes, right this second, your /try page works for me as well. I could try again later on though and it could fail with the same URL tested. It does seem to be a bit odd, it is like your server keeps going down 100 times a day or something. 

Thanks for taking a look, let me know if there is anything I could help with.

**Comment by stefanzweifel** [comment] 2016-08-26 20:22
Hey @zigojacko 

I want to give a short update what I've done / learned so far:

- Tried switching to [nw.js](https://github.com/nwjs/nw.js). Ran into many issues because you would have to rebuild node for your Linux version. Don't know if I should follow that rabbit hole.
- Your posted URLs indeed create errors. As I already said, there's a [very old phantomJs Issue](https://github.com/ariya/phantomjs/issues/12750) about this error. One cause of this error might be Ad-Scripts or sites with a big DOM-tree.

When I open your sites they each create ~200 HTTP requests (~30-40 Javascript Files) and download ~3-10 MB. That's quite a lot of work and Screeenly only runs on a $10 DigitalOcean Server (which was enough for the last 2 years; Server usage is also quite low).

Is screeenly the only service which can't create screenshots of your sites?


(I know this might not be the answer you've hoped for but I'm just not sure if this is really an issue with Screeenly. I will try new solutions over the next days.)

**Comment by stefanzweifel** [comment] 2017-02-20 19:36
I'm closing this issue for now.
I'm still aware that screeenly doesn't work on 100% of all websites but I would like to move on and work on other projects in the future.

I'm still watching / observing projects which do screeeshot generation. If an opportunity opens to implement a new Screenshot Driver which works all the time I will gladly implement it.

**Closed by stefanzweifel** 2017-02-20 19:36 UTC
Labels: duplicate

**Comment by rajpsingh** [comment] 2017-06-13 11:54
You are closing the issue but it's now not working with many other sites.
List somehow is increasing,now.

**Comment by stefanzweifel** [comment] 2017-06-13 12:15
Hey @rajpsingh,

Yeah the issue is closed, but the problem persists. 

I'm currently evaluating how I can implement [Chrome headless](https://developers.google.com/web/updates/2017/04/headless-chrome) as a new ScreenshotDriver. I hope that if we switch to Chrome this problem no longer occurs.

As to the problem itself: I invested roughly 50 hours into debugging, testing different configurations and testing different Drivers. Nothing seemed to work.
The linked [issue](https://github.com/ariya/phantomjs/issues/12750) with PhantomJs is still open and probably will never be closed.
And sadly I don't experience the problem with screeenly in my own projects. At my current job I implemented screeenly in a proejct which now generates ~6'000 Screenshots of smaller and bigger sites. Maybe 1 to 3 requests fail.

I'm still observing and researching on how I could use Chrome Headless with PHP. If I find a suitable solution in the next weeks I would be really happy.
